import { Octokit } from "@octokit/rest";

export function parseRepoUrl(url: string) {
  const match = url.match(/github\.com\/([^/]+)\/([^/.]+)/);
  if (!match) throw new Error("Invalid GitHub repository URL.");
  return { owner: match[1], repo: match[2] };
}

export async function getFileContent(
  octokit: Octokit,
  owner: string,
  repo: string,
  path: string,
  ref?: string
): Promise<string> {
  const response = await octokit.rest.repos.getContent({
    owner,
    repo,
    path,
    ref,
  });
  
  if (Array.isArray(response.data) || response.data.type !== "file") {
    throw new Error(`Path ${path} is not a file.`);
  }
  
  return Buffer.from(response.data.content, "base64").toString("utf-8");
}

export async function createPRWithFiles(
  octokit: Octokit,
  owner: string,
  repo: string,
  baseRef: string,
  branchName: string,
  files: Array<{ path: string; content: string }>,
  prTitle: string
): Promise<string> {
  // 1. Get the SHA of the base reference (e.g., main)
  const baseRefData = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${baseRef}`,
  });
  const baseSha = baseRefData.data.object.sha;

  // 2. Create a new branch
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  // 3. Create blobs for each file
  const treeEntries = await Promise.all(
    files.map(async (file) => {
      const blobData = await octokit.rest.git.createBlob({
        owner,
        repo,
        content: file.content,
        encoding: "utf-8",
      });
      return {
        path: file.path,
        mode: "100644" as const,
        type: "blob" as const,
        sha: blobData.data.sha,
      };
    })
  );

  // 4. Create a new tree
  const treeData = await octokit.rest.git.createTree({
    owner,
    repo,
    base_tree: baseSha,
    tree: treeEntries,
  });

  // 5. Create a commit
  const commitData = await octokit.rest.git.createCommit({
    owner,
    repo,
    message: prTitle,
    tree: treeData.data.sha,
    parents: [baseSha],
  });

  // 6. Update branch to point to new commit
  await octokit.rest.git.updateRef({
    owner,
    repo,
    ref: `heads/${branchName}`,
    sha: commitData.data.sha,
  });

  // 7. Create Pull Request
  const prData = await octokit.rest.pulls.create({
    owner,
    repo,
    title: prTitle,
    head: branchName,
    base: baseRef,
    body: "Tailored resume generated by Gemini Resume Agent.",
  });

  return prData.data.html_url;
}
